"""add video models

Revision ID: 19a325b461e9
Revises: 48040e789ad9
Create Date: 2026-02-04 21:57:41.865256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a325b461e9'
down_revision: Union[str, None] = '48040e789ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('DIRECTOR', 'ACTOR', 'PRODUCER', 'WRITER', name='roletype', native_enum=False), nullable=False),
    sa.Column('character', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casts_movie_id'), 'casts', ['movie_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_movie_id'), 'comments', ['movie_id'], unique=True)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=True)
    op.create_table('subtitles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('language_name', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'language', name='movie_language_uc')
    )
    op.create_index(op.f('ix_subtitles_movie_id'), 'subtitles', ['movie_id'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_format', sa.String(length=10), nullable=True),
    sa.Column('converted_format', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DOWNLOADING', 'CONVERTING', 'READY', 'ERROR', name='statustype', native_enum=False, length=20), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('last_watched_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='check_progress_range'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_movie_id'), 'videos', ['movie_id'], unique=True)
    op.create_table('watch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), nullable=False),
    sa.Column('watch_duration', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'user_id', name='movie_user_uc')
    )
    op.create_index(op.f('ix_watch_history_movie_id'), 'watch_history', ['movie_id'], unique=True)
    op.create_index(op.f('ix_watch_history_user_id'), 'watch_history', ['user_id'], unique=True)
    op.create_index(op.f('ix_watch_history_watched_at'), 'watch_history', ['watched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_history_watched_at'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_user_id'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_movie_id'), table_name='watch_history')
    op.drop_table('watch_history')
    op.drop_index(op.f('ix_videos_movie_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_subtitles_movie_id'), table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_movie_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_casts_movie_id'), table_name='casts')
    op.drop_table('casts')
    op.drop_table('movies')
    # ### end Alembic commands ###
