"""Movie Model updated to fit the search and caching history

Revision ID: 5d15696c7ad6
Revises: 74818825acec
Create Date: 2026-02-05 20:53:03.376912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d15696c7ad6'
down_revision: Union[str, None] = '74818825acec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('search_cache_hits', sa.Integer(), nullable=False, comment='Number of times this movie was returned in search results'))
    op.add_column('movies', sa.Column('last_searched_at', sa.DateTime(), nullable=True, comment='Last time this movie appeared in search results'))
    op.add_column('movies', sa.Column('is_popular', sa.Boolean(), nullable=False, comment='Marked as popular movie (from weekly cron)'))
    op.add_column('movies', sa.Column('popularity_rank', sa.Integer(), nullable=True, comment='Rank in popularity list (lower = more popular)'))
    op.add_column('movies', sa.Column('popularity_score', sa.Float(), nullable=True, comment='Computed popularity score (downloads * rating)'))
    op.add_column('movies', sa.Column('metadata_fetched_at', sa.DateTime(), nullable=True, comment='When full metadata was last fetched from external source'))
    op.add_column('movies', sa.Column('metadata_freshness_days', sa.Integer(), nullable=False, comment='How many days before metadata should be refreshed'))
    op.add_column('movies', sa.Column('search_keywords', postgresql.ARRAY(sa.String(length=100)), nullable=True, comment='Keywords for search optimization'))
    op.alter_column('movies', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Movie plot/summary',
               existing_nullable=True)
    op.alter_column('movies', 'language',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Language code (en, fr, es, etc.)',
               existing_nullable=True)
    op.alter_column('movies', 'imdb_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='IMDb rating (0-10)',
               existing_nullable=True)
    op.alter_column('movies', 'imdb_id',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='IMDb ID (e.g., tt1375666)',
               existing_nullable=True)
    op.alter_column('movies', 'archive_url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='Archive.org details page URL',
               existing_nullable=True)
    op.alter_column('movies', 'downloads',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Download count from source',
               existing_nullable=False)
    op.alter_column('movies', 'num_reviews',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of reviews from source',
               existing_nullable=False)
    op.alter_column('movies', 'torrents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Available torrents with quality, magnet links, seeders, etc.',
               existing_nullable=True)
    op.alter_column('movies', 'downloaded',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether movie file is downloaded and available',
               existing_nullable=False)
    op.alter_column('movies', 'download_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Download status: null, queued, downloading, processing, complete, failed',
               existing_nullable=True)
    op.alter_column('movies', 'download_progress',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Download progress percentage (0-100)',
               existing_nullable=False)
    op.alter_column('movies', 'download_error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if download failed',
               existing_nullable=True)
    op.alter_column('movies', 'file_path',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='Path to downloaded video file on server',
               existing_nullable=True)
    op.alter_column('movies', 'file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Downloaded file size in bytes',
               existing_nullable=True)
    op.alter_column('movies', 'downloaded_quality',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Quality of downloaded file (720p, 1080p, etc.)',
               existing_nullable=True)
    op.alter_column('movies', 'last_watched_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Last time any user watched this movie',
               existing_nullable=True)
    op.alter_column('movies', 'view_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total number of times movie was watched',
               existing_nullable=False)
    op.alter_column('movies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When movie was added to database',
               existing_nullable=False)
    op.alter_column('movies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Last metadata update',
               existing_nullable=False)
    op.drop_index('ix_movies_popular', table_name='movies')
    op.create_index('ix_movies_popular', 'movies', ['popularity_score', 'is_popular'], unique=False)
    op.drop_index('ix_movies_search', table_name='movies')
    op.create_index('ix_movies_search', 'movies', ['title', 'year', 'search_keywords'], unique=False)
    op.create_index('ix_movies_cache', 'movies', ['metadata_fetched_at', 'source'], unique=False)
    op.create_index(op.f('ix_movies_is_popular'), 'movies', ['is_popular'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_is_popular'), table_name='movies')
    op.drop_index('ix_movies_cache', table_name='movies')
    op.drop_index('ix_movies_search', table_name='movies')
    op.create_index('ix_movies_search', 'movies', ['title', 'year'], unique=False)
    op.drop_index('ix_movies_popular', table_name='movies')
    op.create_index('ix_movies_popular', 'movies', ['view_count', 'archive_rating'], unique=False)
    op.alter_column('movies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Last metadata update',
               existing_nullable=False)
    op.alter_column('movies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When movie was added to database',
               existing_nullable=False)
    op.alter_column('movies', 'view_count',
               existing_type=sa.INTEGER(),
               comment='Total number of times movie was watched',
               existing_nullable=False)
    op.alter_column('movies', 'last_watched_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Last time any user watched this movie',
               existing_nullable=True)
    op.alter_column('movies', 'downloaded_quality',
               existing_type=sa.VARCHAR(length=20),
               comment='Quality of downloaded file (720p, 1080p, etc.)',
               existing_nullable=True)
    op.alter_column('movies', 'file_size',
               existing_type=sa.INTEGER(),
               comment='Downloaded file size in bytes',
               existing_nullable=True)
    op.alter_column('movies', 'file_path',
               existing_type=sa.VARCHAR(length=1000),
               comment='Path to downloaded video file on server',
               existing_nullable=True)
    op.alter_column('movies', 'download_error',
               existing_type=sa.TEXT(),
               comment='Error message if download failed',
               existing_nullable=True)
    op.alter_column('movies', 'download_progress',
               existing_type=sa.INTEGER(),
               comment='Download progress percentage (0-100)',
               existing_nullable=False)
    op.alter_column('movies', 'download_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Download status: null, queued, downloading, processing, complete, failed',
               existing_nullable=True)
    op.alter_column('movies', 'downloaded',
               existing_type=sa.BOOLEAN(),
               comment='Whether movie file is downloaded and available',
               existing_nullable=False)
    op.alter_column('movies', 'torrents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Available torrents with quality, magnet links, seeders, etc.',
               existing_nullable=True)
    op.alter_column('movies', 'num_reviews',
               existing_type=sa.INTEGER(),
               comment='Number of reviews from source',
               existing_nullable=False)
    op.alter_column('movies', 'downloads',
               existing_type=sa.INTEGER(),
               comment='Download count from source',
               existing_nullable=False)
    op.alter_column('movies', 'archive_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='Archive.org details page URL',
               existing_nullable=True)
    op.alter_column('movies', 'imdb_id',
               existing_type=sa.VARCHAR(length=20),
               comment='IMDb ID (e.g., tt1375666)',
               existing_nullable=True)
    op.alter_column('movies', 'imdb_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='IMDb rating (0-10)',
               existing_nullable=True)
    op.alter_column('movies', 'language',
               existing_type=sa.VARCHAR(length=10),
               comment='Language code (en, fr, es, etc.)',
               existing_nullable=True)
    op.alter_column('movies', 'description',
               existing_type=sa.TEXT(),
               comment='Movie plot/summary',
               existing_nullable=True)
    op.drop_column('movies', 'search_keywords')
    op.drop_column('movies', 'metadata_freshness_days')
    op.drop_column('movies', 'metadata_fetched_at')
    op.drop_column('movies', 'popularity_score')
    op.drop_column('movies', 'popularity_rank')
    op.drop_column('movies', 'is_popular')
    op.drop_column('movies', 'last_searched_at')
    op.drop_column('movies', 'search_cache_hits')
    # ### end Alembic commands ###
