"""Movie Model updated to fit the archive.org basic and details information of movies

Revision ID: 74818825acec
Revises: d1b72a7a0346
Create Date: 2026-02-05 18:47:19.735053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74818825acec'
down_revision: Union[str, None] = 'd1b72a7a0346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.String(length=255), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.add_column('movies', sa.Column('source', sa.String(length=50), nullable=False, comment='Data source: archive.org, yts, rarbg, etc.'))
    op.add_column('movies', sa.Column('title', sa.String(length=500), nullable=False))
    op.add_column('movies', sa.Column('description', sa.Text(), nullable=True, comment='Movie plot/summary'))
    op.add_column('movies', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('runtime', sa.Integer(), nullable=True, comment='Duration in seconds'))
    op.add_column('movies', sa.Column('director', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('language', sa.String(length=10), nullable=True, comment='Language code (en, fr, es, etc.)'))
    op.add_column('movies', sa.Column('poster_url', sa.String(length=1000), nullable=True))
    op.add_column('movies', sa.Column('archive_rating', sa.Float(), nullable=True, comment='Rating from Archive.org (0-5 stars)'))
    op.add_column('movies', sa.Column('imdb_rating', sa.Float(), nullable=True, comment='IMDb rating (0-10)'))
    op.add_column('movies', sa.Column('imdb_id', sa.String(length=20), nullable=True, comment='IMDb ID (e.g., tt1375666)'))
    op.add_column('movies', sa.Column('archive_url', sa.String(length=1000), nullable=True, comment='Archive.org details page URL'))
    op.add_column('movies', sa.Column('downloads', sa.Integer(), nullable=False, comment='Download count from source'))
    op.add_column('movies', sa.Column('num_reviews', sa.Integer(), nullable=False, comment='Number of reviews from source'))
    op.add_column('movies', sa.Column('torrents', sa.JSON(), nullable=True, comment='Available torrents with quality, magnet links, seeders, etc.'))
    op.add_column('movies', sa.Column('downloaded', sa.Boolean(), nullable=False, comment='Whether movie file is downloaded and available'))
    op.add_column('movies', sa.Column('download_status', sa.String(length=50), nullable=True, comment='Download status: null, queued, downloading, processing, complete, failed'))
    op.add_column('movies', sa.Column('download_progress', sa.Integer(), nullable=False, comment='Download progress percentage (0-100)'))
    op.add_column('movies', sa.Column('download_error', sa.Text(), nullable=True, comment='Error message if download failed'))
    op.add_column('movies', sa.Column('file_path', sa.String(length=1000), nullable=True, comment='Path to downloaded video file on server'))
    op.add_column('movies', sa.Column('file_size', sa.Integer(), nullable=True, comment='Downloaded file size in bytes'))
    op.add_column('movies', sa.Column('downloaded_quality', sa.String(length=20), nullable=True, comment='Quality of downloaded file (720p, 1080p, etc.)'))
    op.add_column('movies', sa.Column('last_watched_at', sa.DateTime(), nullable=True, comment='Last time any user watched this movie'))
    op.add_column('movies', sa.Column('view_count', sa.Integer(), nullable=False, comment='Total number of times movie was watched'))
    op.add_column('movies', sa.Column('created_at', sa.DateTime(), nullable=False, comment='When movie was added to database'))
    op.add_column('movies', sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last metadata update'))
    op.alter_column('movies', 'id',
               existing_type=sa.VARCHAR(),
               comment='Unique identifier from source (Archive.org ID or IMDb ID)',
               existing_nullable=False)
    op.create_index('ix_movies_cleanup', 'movies', ['downloaded', 'last_watched_at'], unique=False, postgresql_where='downloaded = true')
    op.create_index(op.f('ix_movies_downloaded'), 'movies', ['downloaded'], unique=False)
    op.create_index(op.f('ix_movies_imdb_id'), 'movies', ['imdb_id'], unique=True)
    op.create_index(op.f('ix_movies_imdb_rating'), 'movies', ['imdb_rating'], unique=False)
    op.create_index(op.f('ix_movies_language'), 'movies', ['language'], unique=False)
    op.create_index(op.f('ix_movies_last_watched_at'), 'movies', ['last_watched_at'], unique=False)
    op.create_index('ix_movies_popular', 'movies', ['view_count', 'archive_rating'], unique=False)
    op.create_index('ix_movies_search', 'movies', ['title', 'year'], unique=False)
    op.create_index(op.f('ix_movies_source'), 'movies', ['source'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_index(op.f('ix_movies_year'), 'movies', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_source'), table_name='movies')
    op.drop_index('ix_movies_search', table_name='movies')
    op.drop_index('ix_movies_popular', table_name='movies')
    op.drop_index(op.f('ix_movies_last_watched_at'), table_name='movies')
    op.drop_index(op.f('ix_movies_language'), table_name='movies')
    op.drop_index(op.f('ix_movies_imdb_rating'), table_name='movies')
    op.drop_index(op.f('ix_movies_imdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_downloaded'), table_name='movies')
    op.drop_index('ix_movies_cleanup', table_name='movies', postgresql_where='downloaded = true')
    op.alter_column('movies', 'id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Unique identifier from source (Archive.org ID or IMDb ID)',
               existing_nullable=False)
    op.drop_column('movies', 'updated_at')
    op.drop_column('movies', 'created_at')
    op.drop_column('movies', 'view_count')
    op.drop_column('movies', 'last_watched_at')
    op.drop_column('movies', 'downloaded_quality')
    op.drop_column('movies', 'file_size')
    op.drop_column('movies', 'file_path')
    op.drop_column('movies', 'download_error')
    op.drop_column('movies', 'download_progress')
    op.drop_column('movies', 'download_status')
    op.drop_column('movies', 'downloaded')
    op.drop_column('movies', 'torrents')
    op.drop_column('movies', 'num_reviews')
    op.drop_column('movies', 'downloads')
    op.drop_column('movies', 'archive_url')
    op.drop_column('movies', 'imdb_id')
    op.drop_column('movies', 'imdb_rating')
    op.drop_column('movies', 'archive_rating')
    op.drop_column('movies', 'poster_url')
    op.drop_column('movies', 'language')
    op.drop_column('movies', 'director')
    op.drop_column('movies', 'runtime')
    op.drop_column('movies', 'year')
    op.drop_column('movies', 'description')
    op.drop_column('movies', 'title')
    op.drop_column('movies', 'source')
    op.drop_table('movie_genres')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
