"""rename_cast_to_castmember_fix_naming_conflict

Revision ID: a736c17626d4
Revises: 5d15696c7ad6
Create Date: 2026-02-05 21:43:25.165113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a736c17626d4'
down_revision: Union[str, None] = '5d15696c7ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cast_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('DIRECTOR', 'ACTOR', 'PRODUCER', 'WRITER', name='roletype', native_enum=False), nullable=False),
    sa.Column('character', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cast_members_movie_id'), 'cast_members', ['movie_id'], unique=False)
    op.drop_index('ix_casts_movie_id', table_name='casts')
    op.drop_table('casts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('character', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='casts_movie_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='casts_pkey')
    )
    op.create_index('ix_casts_movie_id', 'casts', ['movie_id'], unique=False)
    op.drop_index(op.f('ix_cast_members_movie_id'), table_name='cast_members')
    op.drop_table('cast_members')
    # ### end Alembic commands ###
